"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "./OperationsWorkspace.module.css";
type Application = { id: string; status: string; submittedAt: string; experienceLevel: string; weeklyHours: number; learningGoals: string; user: { name: string; academicEmail: string | null; email: string; studentNumber: string | null; grantBalanceCents: number } };
type Data = { applications: Application[]; summary: { students: number; admitted: number; submitted: number; waitlisted: number; availableFundingCents: number } };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);
export function AdminOverview() {
  const [data, setData] = useState<Data | null>(null); const [ai, setAi] = useState<{ model: string; ready: boolean; connected: boolean | null; connectionMessage: string } | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/university", { cache: "no-store" }); const result = await response.json(); response.ok ? setData(result) : setMessage(result.error); }, []);
  useEffect(() => { const timer = setTimeout(() => { void load(); void fetch("/api/admin/ai-status").then((r) => r.json()).then(setAi); }, 0); return () => clearTimeout(timer); }, [load]);
  async function decide(applicationId: string, status: string) { const response = await fetch("/api/admin/university", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "set_status", applicationId, status, note: "Decision recorded in admissions workspace." }) }); const result = await response.json(); setMessage(response.ok ? `Application moved to ${status}.` : result.error); if (response.ok) await load(); }
  return <section className={styles.workspace}><header className={styles.hero}><div><small>OWNER CONTROL / ADMISSIONS</small><h1>Institutional Operations</h1><p>Applications and AI readiness live here. Curriculum diagnostics and sponsored funding are deliberately separated into their own controlled workspaces.</p></div><b>{ai?.ready ? "AI SERVICE READY" : "AI SETUP REQUIRED"}</b></header>{message && <p className={styles.message}>{message}</p>}<div className={styles.metrics}><article><b>{data?.summary.students || 0}</b><span>STUDENTS</span></article><article><b>{data?.summary.admitted || 0}</b><span>ADMITTED</span></article><article><b>{(data?.summary.submitted || 0) + (data?.summary.waitlisted || 0)}</b><span>NEEDS DECISION</span></article><article><b>{money(data?.summary.availableFundingCents || 0)}</b><span>AVAILABLE SPONSORED BALANCES</span></article></div><section className={styles.policy}><header><small>GEMINI ASSESSMENT SERVICE</small><h2>{ai?.model || "Checking protected configuration…"}</h2><p>{ai?.connectionMessage}</p></header></section><div className={styles.table}><div className={`${styles.tableHead} ${styles.fundingHead}`}><span>STUDENT</span><span>STATUS</span><span>ACADEMIC INTENT</span><span>SUBMITTED</span><span>DECISION</span></div>{data?.applications.map((application) => <article className={`${styles.row} ${styles.fundingRow}`} key={application.id}><span><b>{application.user.name}</b><small>{application.user.studentNumber || application.user.academicEmail || application.user.email}</small></span><strong data-status={application.status}>{application.status}</strong><span>{application.learningGoals}</span><span>{new Date(application.submittedAt).toLocaleDateString()}</span><span><button onClick={() => void decide(application.id, "ADMITTED")}>ADMIT</button> <button onClick={() => void decide(application.id, "WAITLISTED")}>WAITLIST</button></span></article>)}</div></section>;
}
