"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./OperationsWorkspace.module.css";

type Attempt = { id: string; outcome: string; mode: string; httpStatus: number | null; errorMessage: string | null; startedAt: string; revisionId: string | null };
type Source = { id: string; wikiTitle: string; url: string; syncStatus: string; statusWarnings: string[]; sourceExcerpt: string; revisionId: string | null; lastGoodRevisionId: string | null; lastAttemptAt: string | null; lastSuccessAt: string | null; lastHttpStatus: number | null; lastErrorCode: string | null; lastErrorMessage: string | null; consecutiveFailures: number; bypassReason: string | null; mappings: { course: { id: string; code: string; title: string } }[]; attempts: Attempt[] };
type Data = { items: Source[]; total: number; page: number; pages: number; counts: { syncStatus: string; _count: number }[]; courses: { id: string; code: string; title: string }[] };

export function CurriculumSources() {
  const [data, setData] = useState<Data | null>(null); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [courseId, setCourseId] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [open, setOpen] = useState<Source | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const query = new URLSearchParams({ page: String(page), search, status, courseId }); const response = await fetch(`/api/admin/curriculum/sources?${query}`, { cache: "no-store" }); const result = await response.json(); response.ok ? setData(result) : setMessage(result.error); }, [page, search, status, courseId]);
  useEffect(() => { const timer = setTimeout(() => void load(), 200); return () => clearTimeout(timer); }, [load]);
  const count = useMemo(() => Object.fromEntries(data?.counts.map((item) => [item.syncStatus, item._count]) || []), [data]);
  async function sync(ids: string[], force = false) { setMessage(force ? "Force-updating selected sources…" : "Retrying selected sources…"); const response = await fetch("/api/admin/curriculum/sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: force ? "force" : "retry", ids }) }); const result = await response.json(); setMessage(response.ok ? `${result.updated} updated · ${result.failed} need review` : result.error); setSelected([]); await load(); }
  async function sourceAction(action: string, payload: Record<string, unknown> = {}) { if (!open) return; const response = await fetch(`/api/admin/curriculum/sources/${open.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const result = await response.json(); setMessage(response.ok ? `${open.wikiTitle}: ${action} recorded.` : result.error); if (response.ok) { setOpen(result.source); await load(); } }
  return <section className={styles.workspace}><header className={styles.hero}><div><small>ACADEMIC OPERATIONS / SOURCE AUTHORITY</small><h1>Curriculum Sources</h1><p>Diagnose official Bohemia sources, preserve the last-good technical record, and maintain many-to-many course grounding without touching faculty-authored instruction.</p></div><button onClick={() => void fetch("/api/admin/curriculum/sync", { method: "POST" }).then(() => load())}>SYNC ALL OFFICIAL SOURCES</button></header>
    <div className={styles.metrics}><article><b>{data?.total || 0}</b><span>IN CURRENT VIEW</span></article><article><b>{count.FAILED || 0}</b><span>FAILED</span></article><article><b>{count.WARNING || 0}</b><span>WARNINGS</span></article><article><b>{count.BYPASSED || 0}</b><span>ACCEPTED LAST-GOOD</span></article></div>
    <div className={styles.filters}><label>SEARCH<input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Wiki title or URL"/></label><label>STATUS<select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option>ALL</option>{["FAILED","WARNING","CURRENT","UPDATED","BYPASSED","DISABLED"].map((item) => <option key={item}>{item}</option>)}</select></label><label>COURSE<select value={courseId} onChange={(e) => { setCourseId(e.target.value); setPage(1); }}><option value="">ALL COURSES</option>{data?.courses.map((course) => <option value={course.id} key={course.id}>{course.code} · {course.title}</option>)}</select></label></div>
    {message && <p className={styles.message}>{message}</p>}
    <div className={styles.bulk}><span>{selected.length} SELECTED</span><button disabled={!selected.length} onClick={() => void sync(selected)}>RETRY</button><button disabled={!selected.length} onClick={() => void sync(selected, true)}>FORCE UPDATE</button></div>
    <div className={styles.table}><div className={styles.tableHead}><span/><span>SOURCE</span><span>MAPPED COURSES</span><span>LAST SUCCESS</span><span>STATUS</span></div>{data?.items.map((source) => <button className={styles.row} key={source.id} onClick={() => setOpen(source)}><input aria-label={`Select ${source.wikiTitle}`} type="checkbox" checked={selected.includes(source.id)} onClick={(e) => e.stopPropagation()} onChange={(e) => setSelected((current) => e.target.checked ? [...current, source.id] : current.filter((id) => id !== source.id))}/><span><b>{source.wikiTitle}</b><small>{source.lastErrorMessage || source.statusWarnings.join(" · ") || "No active warning"}</small></span><span>{source.mappings.length ? source.mappings.map((mapping) => mapping.course.code).join(", ") : "UNMAPPED"}</span><span>{source.lastSuccessAt ? new Date(source.lastSuccessAt).toLocaleString() : "NEVER"}</span><strong data-status={source.syncStatus}>{source.syncStatus}</strong></button>)}</div>
    <nav className={styles.pagination}><button disabled={page <= 1} onClick={() => setPage(page - 1)}>← PREVIOUS</button><span>PAGE {data?.page || 1} OF {data?.pages || 1}</span><button disabled={page >= (data?.pages || 1)} onClick={() => setPage(page + 1)}>NEXT →</button></nav>
    {open && <div className={styles.drawerBack} onClick={() => setOpen(null)}><aside className={styles.drawer} onClick={(e) => e.stopPropagation()}><button className={styles.close} onClick={() => setOpen(null)}>×</button><small>SOURCE DIAGNOSTIC</small><h2>{open.wikiTitle}</h2><a href={open.url} target="_blank" rel="noreferrer">OPEN APPROVED WIKI PAGE ↗</a><div className={styles.diagnostics}><span><small>HTTP</small><b>{open.lastHttpStatus || "—"}</b></span><span><small>FAILURES</small><b>{open.consecutiveFailures}</b></span><span><small>CURRENT REVISION</small><b>{open.revisionId || "—"}</b></span><span><small>LAST GOOD</small><b>{open.lastGoodRevisionId || "—"}</b></span></div><section><small>WHY THIS NEEDS ATTENTION</small><p>{open.lastErrorMessage || open.statusWarnings.join(" · ") || "This source has no active warning."}</p><code>{open.lastErrorCode || open.syncStatus}</code></section><section><small>LAST-GOOD EXCERPT</small><p>{open.sourceExcerpt}</p></section><form onSubmit={(e) => { e.preventDefault(); const form = new FormData(e.currentTarget); void sourceAction("correct", { wikiTitle: form.get("wikiTitle"), url: form.get("url"), courseIds: form.getAll("courseIds") }); }}><label>WIKI TITLE<input name="wikiTitle" defaultValue={open.wikiTitle}/></label><label>APPROVED BOHEMIA URL<input name="url" defaultValue={open.url}/></label><label>COURSE MAPPINGS<select name="courseIds" multiple defaultValue={open.mappings.map((item) => item.course.id)}>{data?.courses.map((course) => <option value={course.id} key={course.id}>{course.code} · {course.title}</option>)}</select></label><button>SAVE CORRECTION</button></form><div className={styles.actions}><button onClick={() => void sync([open.id])}>RETRY</button><button onClick={() => void sync([open.id], true)}>FORCE UPDATE</button><button onClick={() => { const reason = prompt("Required bypass reason"); if (reason) void sourceAction("bypass", { reason }); }}>BYPASS WARNING</button><button onClick={() => { const reason = prompt("Required disable reason"); if (reason) void sourceAction("disable", { reason }); }}>DISABLE SOURCE</button></div><section><small>SYNC HISTORY</small>{open.attempts.map((attempt) => <p key={attempt.id}><b>{attempt.outcome}</b> · {attempt.mode} · {new Date(attempt.startedAt).toLocaleString()}<br/>{attempt.errorMessage}</p>)}</section></aside></div>}
  </section>;
}
