"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "./OperationsWorkspace.module.css";
type Entry = { id: string; type: string; amountCents: number; description: string; createdAt: string; user: { name: string; studentNumber: string | null } };
type Data = { items: Entry[]; total: number; page: number; pages: number; courses: { id: string; code: string; title: string }[]; policy: { name: string; timeTiers: { throughHours: number | null; refundPercent: number }[]; progressTiers: { throughPercent: number; refundPercent: number }[]; penaltyTiers: { refundPercent: number; penaltyBps: number }[] } };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
export function FundingOperations() {
  const [data, setData] = useState<Data | null>(null); const [page, setPage] = useState(1); const [student, setStudent] = useState(""); const [type, setType] = useState("ALL"); const [courseId, setCourseId] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const q = new URLSearchParams({ page: String(page), student, type, courseId, from, to }); const response = await fetch(`/api/admin/funding?${q}`, { cache: "no-store" }); const result = await response.json(); response.ok ? setData(result) : setMessage(result.error); }, [page, student, type, courseId, from, to]);
  useEffect(() => { const timer = setTimeout(() => void load(), 200); return () => clearTimeout(timer); }, [load]);
  return <section className={styles.workspace}><header className={styles.hero}><div><small>FINANCIAL OPERATIONS / INTERNAL SPONSORSHIP</small><h1>Funding Ledger</h1><p>Filter the complete noncash sponsored-learning record. Withdrawal returns retain the exact policy snapshot applied at confirmation.</p></div><b>{data?.total || 0} TRANSACTIONS</b></header><div className={styles.filters}><label>STUDENT<input value={student} onChange={(e) => setStudent(e.target.value)} placeholder="Name or student ID"/></label><label>TRANSACTION<select value={type} onChange={(e) => setType(e.target.value)}><option>ALL</option>{["INITIAL_AWARD","TERM_AWARD","JUST_IN_TIME_AWARD","COURSE_ALLOCATION","WITHDRAWAL_REFUND","ADJUSTMENT","CORRECTION"].map((item) => <option key={item}>{item}</option>)}</select></label><label>COURSE<select value={courseId} onChange={(e) => setCourseId(e.target.value)}><option value="">ALL COURSES</option>{data?.courses.map((course) => <option value={course.id} key={course.id}>{course.code} · {course.title}</option>)}</select></label><label>FROM<input type="date" value={from} onChange={(e) => setFrom(e.target.value)}/></label><label>TO<input type="date" value={to} onChange={(e) => setTo(e.target.value)}/></label></div>{message && <p className={styles.message}>{message}</p>}<section className={styles.policy}><header><small>EFFECTIVE WITHDRAWAL POLICY</small><h2>{data?.policy.name}</h2></header><div><article><b>TIME SCALE</b>{data?.policy.timeTiers.map((tier) => <span key={String(tier.throughHours)}>Through {tier.throughHours ? `${tier.throughHours} hours` : "remainder"}: {tier.refundPercent}%</span>)}</article><article><b>PROGRESS SCALE</b>{data?.policy.progressTiers.map((tier) => <span key={tier.throughPercent}>Through {tier.throughPercent}%: {tier.refundPercent}%</span>)}</article><article><b>RENEWAL IMPACT</b>{data?.policy.penaltyTiers.map((tier) => <span key={tier.refundPercent}>{tier.refundPercent}% return: {tier.penaltyBps / 100} points</span>)}</article></div></section><div className={styles.table}><div className={`${styles.tableHead} ${styles.fundingHead}`}><span>STUDENT</span><span>TYPE</span><span>DESCRIPTION</span><span>DATE</span><span>AMOUNT</span></div>{data?.items.map((entry) => <article className={`${styles.row} ${styles.fundingRow}`} key={entry.id}><span><b>{entry.user.name}</b><small>{entry.user.studentNumber || "ID PENDING"}</small></span><span>{entry.type.replaceAll("_", " ")}</span><span>{entry.description}</span><span>{new Date(entry.createdAt).toLocaleDateString()}</span><strong data-negative={entry.amountCents < 0}>{entry.amountCents > 0 ? "+" : ""}{money(entry.amountCents)}</strong></article>)}</div><nav className={styles.pagination}><button disabled={page <= 1} onClick={() => setPage(page - 1)}>← PREVIOUS</button><span>PAGE {data?.page || 1} OF {data?.pages || 1}</span><button disabled={page >= (data?.pages || 1)} onClick={() => setPage(page + 1)}>NEXT →</button></nav></section>;
}
