"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "./FundingOperations.module.css";
type Entry = { id: string; type: string; amountCents: number; description: string; createdAt: string; user: { name: string; studentNumber: string | null } };
type Award = { id: string; referenceNumber: string; sourceName: string; type: string; status: string; originalAmountCents: number; remainingAmountCents: number; publicDescription: string; restrictions: string; issuingDepartment: string; expiresAt: string | null };
type Student = { id: string; name: string; studentNumber: string | null; grantBalanceCents: number };
type Data = { items: Entry[]; total: number; page: number; pages: number; courses: { id: string; code: string; title: string }[]; policy: { name: string } };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
export function FundingOperations() {
  const [data,setData]=useState<Data|null>(null); const [students,setStudents]=useState<Student[]>([]); const [permissions,setPermissions]=useState<string[]>([]); const [account,setAccount]=useState<{balanceCents:number;sourceAvailableCents:number;varianceCents:number;reconciled:boolean;awards:Award[]}|null>(null); const [page,setPage]=useState(1); const [student,setStudent]=useState(""); const [studentId,setStudentId]=useState(""); const [type,setType]=useState("ALL"); const [message,setMessage]=useState(""); const [draft,setDraft]=useState({sourceName:"Thunder Buddies Studios Sponsored Learning Award",amount:"",type:"INTERNAL_GRANT",expiresAt:"",publicDescription:"Internal sponsored-learning value issued for eligible university services.",restrictions:"Eligible Enfusion University courses and credential services only; noncashable and nontransferable.",issuingDepartment:"University Sponsorship Office",reason:"APPLICATION_AWARD",internalNote:""});
  const loadLedger=useCallback(async()=>{const q=new URLSearchParams({page:String(page),student,type});const response=await fetch(`/api/admin/funding?${q}`,{cache:"no-store"});const result=await response.json();response.ok?setData(result):setMessage(result.error)},[page,student,type]);
  const loadAccount=useCallback(async(id:string)=>{if(!id){setAccount(null);return}const response=await fetch(`/api/admin/funding/awards?studentId=${id}`,{cache:"no-store"});const result=await response.json();response.ok?setAccount(result):setMessage(result.error)},[]);
  useEffect(()=>{const timer=setTimeout(()=>void loadLedger(),0);return()=>clearTimeout(timer)},[loadLedger]); useEffect(()=>{const timer=setTimeout(()=>void fetch("/api/admin/funding/awards",{cache:"no-store"}).then(r=>r.json().then(x=>({ok:r.ok,x}))).then(({ok,x})=>{if(ok){setStudents(x.students);setPermissions(x.permissions)}else setMessage(x.error)}),0);return()=>clearTimeout(timer)},[]); useEffect(()=>{const timer=setTimeout(()=>void loadAccount(studentId),0);return()=>clearTimeout(timer)},[studentId,loadAccount]);
  async function issue(event:FormEvent){event.preventDefault();setMessage("");const response=await fetch("/api/admin/funding/awards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"ISSUE",userId:studentId,...draft,amountCents:Math.round(Number(draft.amount)*100),idempotencyKey:crypto.randomUUID()})});const result=await response.json();setMessage(response.ok?"Award issued and permanently recorded.":result.error);if(response.ok){setDraft({...draft,amount:"",internalNote:""});await loadAccount(studentId);await loadLedger()}}
  async function mutate(award:Award,action:string){const answer=window.prompt(action==="ADJUST"?"Enter the new available amount in dollars:":"Enter a student-visible reason for this action:",action==="ADJUST"?String(award.remainingAmountCents/100):"");if(answer===null)return;const publicReason=action==="ADJUST"?window.prompt("Explain this correction to the student:","Administrative correction to the internal sponsored-learning source."):answer;if(!publicReason)return;const response=await fetch("/api/admin/funding/awards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,awardId:award.id,amountCents:action==="ADJUST"?Math.round(Number(answer)*100):undefined,reason:"DATA_CORRECTION",publicReason,internalNote:"Recorded through Funding Operations",idempotencyKey:crypto.randomUUID()})});const result=await response.json();setMessage(response.ok?"Funding source updated and audited.":result.error);if(response.ok){await loadAccount(studentId);await loadLedger()}}
  return <main className={styles.workspace}><header><div><small>SPONSORED-LEARNING OPERATIONS</small><h1>Funding administration</h1><p>Reconcile source awards, immutable activity, permissions, and documented corrections. No action creates student debt or a cash balance.</p></div><b>{data?.total||0} TRANSACTIONS</b></header>{message&&<p className={styles.notice} role="status">{message}</p>}
    <section className={styles.controls}><label>STUDENT RECORD<select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Choose a student</option>{students.map(item=><option value={item.id} key={item.id}>{item.name} · {item.studentNumber||"ID pending"}</option>)}</select></label>{account&&<div className={styles.reconcile}><span><small>USER BALANCE</small><b>{money(account.balanceCents)}</b></span><span><small>SOURCE TOTAL</small><b>{money(account.sourceAvailableCents)}</b></span><span data-valid={account.reconciled}><small>RECONCILIATION</small><b>{account.reconciled?"BALANCED":`${money(account.varianceCents)} variance`}</b></span></div>}</section>
    {studentId&&<div className={styles.split}><section><h2>Funding sources</h2>{account?.awards.map(award=><article className={styles.award} key={award.id}><div><small>{award.type.replaceAll("_"," ")} · {award.referenceNumber}</small><h3>{award.sourceName}</h3><p>{award.publicDescription}</p></div><strong>{money(award.remainingAmountCents)}<small>of {money(award.originalAmountCents)}</small></strong><footer><span>{award.status.replaceAll("_"," ")}</span>{permissions.includes("ADJUST")&&<button onClick={()=>void mutate(award,"ADJUST")}>Adjust</button>}{permissions.includes("SUSPEND")&&<button onClick={()=>void mutate(award,award.status==="SUSPENDED"?"RESUME":"SUSPEND")}>{award.status==="SUSPENDED"?"Resume":"Suspend"}</button>}{permissions.includes("REVERSE_UNUSED")&&award.remainingAmountCents>0&&<button onClick={()=>void mutate(award,"REVERSE_UNUSED")}>Reverse unused</button>}</footer></article>)}</section>{permissions.includes("ISSUE")&&<form className={styles.issue} onSubmit={issue}><small>NEW SOURCE RECORD</small><h2>Issue sponsored value</h2><label>Source name<input required value={draft.sourceName} onChange={e=>setDraft({...draft,sourceName:e.target.value})}/></label><div><label>Classification<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{["INTERNAL_SCHOLARSHIP","INTERNAL_GRANT","UNIVERSITY_CREDIT","PROGRAM_FUNDING","EMPLOYER_SPONSORSHIP","PROMOTIONAL_AWARD","REFUND","ADMINISTRATIVE_ADJUSTMENT","TRANSFER_VALUE","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><label>Value (USD)<input required type="number" min="0.01" step="0.01" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label></div><label>Student description<textarea required value={draft.publicDescription} onChange={e=>setDraft({...draft,publicDescription:e.target.value})}/></label><label>Restrictions<textarea required value={draft.restrictions} onChange={e=>setDraft({...draft,restrictions:e.target.value})}/></label><div><label>Issuing department<input required value={draft.issuingDepartment} onChange={e=>setDraft({...draft,issuingDepartment:e.target.value})}/></label><label>Expiration<input type="date" value={draft.expiresAt} onChange={e=>setDraft({...draft,expiresAt:e.target.value})}/></label></div><label>Private administrative note<textarea value={draft.internalNote} onChange={e=>setDraft({...draft,internalNote:e.target.value})}/></label><button>Confirm and issue award</button></form>}</div>}
    <FundingPermissionPanel />
    <section className={styles.ledger}><header><div><small>IMMUTABLE ACCOUNT ACTIVITY</small><h2>Reconciled ledger</h2></div><div><input value={student} onChange={e=>setStudent(e.target.value)} placeholder="Search student"/><select value={type} onChange={e=>setType(e.target.value)}><option>ALL</option>{["INITIAL_AWARD","TERM_AWARD","JUST_IN_TIME_AWARD","COURSE_ALLOCATION","WITHDRAWAL_REFUND","ADJUSTMENT","REVERSAL","CORRECTION"].map(x=><option key={x}>{x}</option>)}</select></div></header>{data?.items.map(entry=><article key={entry.id}><span><b>{entry.user.name}</b><small>{entry.user.studentNumber||"ID pending"}</small></span><span>{entry.type.replaceAll("_"," ")}</span><span>{entry.description}</span><time>{new Date(entry.createdAt).toLocaleDateString()}</time><strong data-negative={entry.amountCents<0}>{entry.amountCents>0?"+":""}{money(entry.amountCents)}</strong></article>)}<nav><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {data?.page||1} of {data?.pages||1}</span><button disabled={page>=(data?.pages||1)} onClick={()=>setPage(page+1)}>Next</button></nav></section>
  </main>;
}

type StaffMember = { id:string; name:string; role:string; academicEmail:string|null; fundingPermissions:{capability:string}[] };
function FundingPermissionPanel(){
  const [staff,setStaff]=useState<StaffMember[]>([]); const [visible,setVisible]=useState(false); const capabilities=["ISSUE","EDIT_DETAILS","ADJUST","REVERSE_UNUSED","SUSPEND"];
  const load=useCallback(async()=>{const response=await fetch("/api/admin/funding/awards",{cache:"no-store"});const result=await response.json();if(response.ok){setVisible(Boolean(result.canManagePermissions));setStaff(result.staff||[])}},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function toggle(member:StaffMember,capability:string){const granted=!member.fundingPermissions.some(item=>item.capability===capability);const response=await fetch("/api/admin/funding/awards",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId:member.id,capability,granted})});if(response.ok)await load()}
  if(!visible)return null;
  return <section className={styles.permissions}><header><small>OWNER-CONTROLLED AUTHORITY</small><h2>Funding permissions</h2><p>Administrators receive View and Note. Every balance-changing capability requires an explicit owner grant.</p></header>{staff.map(member=><article key={member.id}><span><b>{member.name}</b><small>{member.role} · {member.academicEmail||"No campus ID"}</small></span><div>{capabilities.map(capability=><button data-active={member.fundingPermissions.some(item=>item.capability===capability)} onClick={()=>void toggle(member,capability)} key={capability}>{capability.replaceAll("_"," ")}</button>)}</div></article>)}</section>;
}
