"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./GuideAcademy.module.css";
type Guide = { id: string; audience: string; title: string; summary: string; category: string; route: string | null; steps: { id: string; stepNumber: number; title: string; instruction: string; progress: { completedAt: string }[] }[] };
export function GuideAcademy({ audience }: { audience?: "FACULTY" | "ADMIN" }) {
  const [guides, setGuides] = useState<Guide[]>([]); const [search, setSearch] = useState(""); const [open, setOpen] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/guides", { cache: "no-store" }); const result = await response.json(); if (response.ok) setGuides(result.guides); }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => guides.filter((guide) => (!audience || guide.audience === audience) && `${guide.title} ${guide.summary} ${guide.category}`.toLowerCase().includes(search.toLowerCase())), [guides, audience, search]);
  async function toggle(step: Guide["steps"][number]) { await fetch("/api/guides", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ guideStepId: step.id, completed: !step.progress.length }) }); await load(); }
  return <section className={styles.academy}><header><div><small>{audience === "FACULTY" ? "FACULTY ACADEMY" : "ADMINISTRATOR ACADEMY"}</small><h1>Learn the institution by doing the work.</h1><p>Task-based guides connect directly to the controls they explain. Complete steps at your own pace and return whenever the system changes.</p></div><label>SEARCH GUIDES<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Admissions, Gemini, credentials…"/></label></header><div className={styles.grid}>{filtered.map((guide) => { const complete = guide.steps.filter((step) => step.progress.length).length; const expanded = open === guide.id; return <article key={guide.id}><button className={styles.card} onClick={() => setOpen(expanded ? null : guide.id)}><small>{guide.category} / {guide.audience}</small><h2>{guide.title}</h2><p>{guide.summary}</p><span><i style={{ width: `${guide.steps.length ? complete / guide.steps.length * 100 : 0}%` }}/></span><b>{complete} OF {guide.steps.length} STEPS COMPLETE</b></button>{expanded && <div className={styles.steps}>{guide.steps.map((step) => <label key={step.id}><input type="checkbox" checked={Boolean(step.progress.length)} onChange={() => void toggle(step)}/><span><small>STEP {step.stepNumber}</small><b>{step.title}</b><p>{step.instruction}</p></span></label>)}{guide.route && <Link href={guide.route}>OPEN THE CORRESPONDING WORKSPACE →</Link>}</div>}</article>; })}</div></section>;
}
