"use client";

import { useEffect, useState } from "react";
import styles from "./StudentProfile.module.css";

type Tracking = { id: string; trackingNumber: string; type: string; status: string; outcome: string | null; submittedAt: string; closedAt: string | null; statusHistory: { status: string; detail?: string | null; at: string }[]; programApplication: { program: { code: string; title: string } } | null };
type ProfileData = { user: { name: string; email: string; academicEmail: string | null; studentNumber: string | null; specialty: string | null; createdAt: string; grantBalanceCents: number; studentApplication: { preferredName: string | null; country: string; timeZone: string; experienceLevel: string; weeklyHours: number } | null; courseEnrollments: { id: string; status: string; progress: number; course: { code: string; title: string } }[]; programEnrollments: { id: string; status: string; creditsEarned: number; program: { code: string; title: string; level: string; academy: string; creditsRequired: number } }[]; certificates: { id: string; title: string; credentialCode: string; issuedAt: string; learningCredits: number }[]; applicationTrackers: Tracking[] }; standing: { status: string; gradeAverage: number; finalizedGradeCount: number; renewalMultiplierBps: number; withdrawalCount: number } };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);

export function StudentProfile() {
  const [data, setData] = useState<ProfileData | null>(null); const [error, setError] = useState("");
  useEffect(() => { const timer = setTimeout(() => void fetch("/api/university/profile").then(async (response) => { const result = await response.json(); if (response.ok) setData(result); else setError(result.error); }), 0); return () => clearTimeout(timer); }, []);
  if (!data) return <div className={styles.loading}>{error || "ASSEMBLING YOUR STUDENT RECORD"}</div>;
  const { user, standing } = data; const initials = user.name.split(" ").map((part) => part[0]).slice(0,2).join("");
  return <section className={styles.profile}>
    <header className={styles.identity}><div className={styles.portrait}>{initials}<i/></div><div><p>OFFICIAL ENFUSION UNIVERSITY STUDENT PROFILE</p><h1>{user.name}</h1><span>{user.specialty || "Enfusion development student"}</span><div><b>{user.academicEmail}</b><small>ACADEMIC LOGIN</small></div></div><aside><small>STUDENT IDENTIFICATION NUMBER</small><b>{user.studentNumber || "PENDING"}</b><span>Issued {new Date(user.createdAt).toLocaleDateString()}</span><i>ACTIVE STUDENT RECORD</i></aside></header>
    <div className={styles.profileRibbon}><span><small>ACADEMIC STANDING</small><b>{standing.status.replaceAll("_", " ")}</b></span><span><small>FINALIZED AVERAGE</small><b>{standing.finalizedGradeCount ? `${standing.gradeAverage.toFixed(1)}%` : "—"}</b></span><span><small>SPONSORSHIP RATE</small><b>{standing.renewalMultiplierBps / 100}%</b></span><span><small>AVAILABLE FUNDING</small><b>{money(user.grantBalanceCents)}</b></span><span><small>CREDENTIALS</small><b>{user.certificates.length}</b></span></div>
    <div className={styles.profileGrid}><main><section><header><small>PROGRAM RECORD</small><h2>Academic pathways</h2></header>{user.programEnrollments.map((item) => <article className={styles.program} key={item.id}><span>{item.program.code}</span><div><small>{item.program.academy} / {item.program.level}</small><h3>{item.program.title}</h3><p>{item.creditsEarned} of {item.program.creditsRequired} learning credits recorded</p><i><b style={{ width: `${Math.min(100,item.creditsEarned / Math.max(1,item.program.creditsRequired) * 100)}%` }}/></i></div><em>{item.status}</em></article>)}{!user.programEnrollments.length && <p className={styles.empty}>No active academic program. Explore Programs to submit a tracked application.</p>}</section><section><header><small>COURSE RECORD</small><h2>Learning activity</h2></header><div className={styles.courses}>{user.courseEnrollments.slice(0,12).map((item) => <article key={item.id}><span>{item.course.code}</span><b>{item.course.title}</b><small>{item.status} · {item.progress}% complete</small></article>)}</div></section></main><aside><section><small>PERSONAL ACADEMIC RECORD</small><h2>Profile details</h2><dl><div><dt>Recovery email</dt><dd>{user.email}</dd></div><div><dt>Country</dt><dd>{user.studentApplication?.country || "Not recorded"}</dd></div><div><dt>Time zone</dt><dd>{user.studentApplication?.timeZone || "Not recorded"}</dd></div><div><dt>Experience level</dt><dd>{user.studentApplication?.experienceLevel || "Not recorded"}</dd></div><div><dt>Weekly availability</dt><dd>{user.studentApplication?.weeklyHours || 0} hours</dd></div></dl></section><section><small>VERIFIED COMPLETION</small><h2>Credentials</h2>{user.certificates.slice(0,6).map((item) => <article className={styles.credential} key={item.id}><b>{item.title}</b><span>{item.credentialCode}</span><small>{new Date(item.issuedAt).toLocaleDateString()} · {item.learningCredits} credits</small></article>)}{!user.certificates.length && <p>No credentials have been issued yet.</p>}</section></aside></div>
    <section className={styles.tracker}><header><div><small>APPLICATION HISTORY</small><h2>Tracking numbers and decisions</h2></div><span>{user.applicationTrackers.length} RECORDS</span></header>{user.applicationTrackers.map((item) => <article key={item.id}><div><small>{item.type}</small><b>{item.programApplication?.program.title || "Enfusion University Admission"}</b><code>{item.trackingNumber}</code></div><ol>{item.statusHistory.map((event) => <li key={`${event.status}-${event.at}`}><i/><div><b>{event.status.replaceAll("_", " ")}</b><span>{event.detail}</span><time>{new Date(event.at).toLocaleString()}</time></div></li>)}</ol><aside><span data-status={item.status}>{item.status}</span><b>{item.outcome || "Decision pending"}</b>{item.closedAt && <small>Tracking closed {new Date(item.closedAt).toLocaleDateString()}</small>}</aside></article>)}</section>
  </section>;
}
