"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./UniversityLearning.module.css";

type Enrollment = { id: string; status: string; progress: number };
type Course = { id: string; code: string; title: string; summary: string; deliverable: string; studio: string; level: string; academy: string; estimatedDays: number; workloadHours: number; learningCredits: number; serviceValueCents: number; completedDays: number; enrollments: Enrollment[]; prerequisites: { prerequisite: { id: string; code: string; title: string } }[]; sources: { syncStatus: string; statusWarnings: string[] }[]; _count: { enrollments: number; days: number } };
type Curriculum = { courses: Course[]; academies: string[]; enrolled: Course[]; nextCourse: Course | null; grantBalanceCents: number; coverage: { mapped: number; total: number } };
type CourseDay = { id: string; dayNumber: number; title: string; objectives: string[]; instructionalText: string; sourceSection: string; workbenchSteps: string[]; practicalLab: string; completionChecklist: string[]; knowledgeQuestion: string; reflectionPrompt: string; progress: { completed: boolean; reflection: string | null }[] };
type CourseDetail = Course & { days: CourseDay[]; sources: { wikiTitle: string; url: string; sourceExcerpt: string; syncStatus: string; statusWarnings: string[]; revisionId: string | null }[] };
type AcademyData = { submissions: { id: string; title: string; status: string; feedback: string | null; course: { code: string; title: string } }[]; certificates: { id: string; credentialCode: string; title: string; issuer: string; issuedAt: string; learningCredits: number }[]; programs: { id: string; code: string; title: string; summary: string; level: string; creditsRequired: number; sponsoredBy: string }[]; learningCredits: number };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);

export function UniversityLearning({ view, userName }: { view: "dashboard" | "catalog" | "programs" | "submissions" | "credentials"; userName: string }) {
  const [data, setData] = useState<Curriculum | null>(null); const [records, setRecords] = useState<AcademyData | null>(null); const [selected, setSelected] = useState<CourseDetail | null>(null); const [search, setSearch] = useState(""); const [academy, setAcademy] = useState("ALL"); const [level, setLevel] = useState("ALL"); const [error, setError] = useState("");
  const load = useCallback(async () => { const [curriculumResponse, academyResponse] = await Promise.all([fetch("/api/curriculum"), fetch("/api/academy")]); const curriculum = await curriculumResponse.json(); const academyResult = await academyResponse.json(); if (!curriculumResponse.ok) { setError(curriculum.error || "Curriculum unavailable."); return; } setData(curriculum); if (academyResponse.ok) setRecords(academyResult); }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function openCourse(id: string) { const response = await fetch(`/api/curriculum/${id}`); const result = await response.json(); if (response.ok) setSelected(result.course); else setError(result.error); }
  async function enroll(course: Course) { const response = await fetch("/api/academy", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "enroll_course", courseId: course.id }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } await load(); await openCourse(course.id); }
  const filtered = useMemo(() => data?.courses.filter((course) => (academy === "ALL" || course.academy === academy) && (level === "ALL" || course.level === level) && `${course.code} ${course.title} ${course.summary}`.toLowerCase().includes(search.toLowerCase())) || [], [data, academy, level, search]);
  if (!data) return <div className={styles.loading}>{error || "OPENING ENFUSION UNIVERSITY…"}</div>;
  if (selected) return <CoursePlayer course={selected} close={() => { setSelected(null); void load(); }} refresh={() => openCourse(selected.id)} />;

  if (view === "dashboard") return <section className={styles.learning}><div className={styles.welcome}><div><p>ENFUSION UNIVERSITY · STUDENT HOME</p><h1>Welcome back, <em>{userName.split(" ")[0]}.</em></h1><span>Continue your studio curriculum, review faculty activity, and move one documented Workbench objective forward today.</span></div><aside><small>SPONSORED LEARNING BALANCE</small><strong>{money(data.grantBalanceCents)}</strong><span>Non-cash balance · student amount due $0</span></aside></div><div className={styles.focus}><section><header className={styles.sectionTitle}><h2>Continue learning</h2><span>{data.enrolled.length} ACTIVE COURSES</span></header>{data.enrolled.slice(0, 4).map((course) => <div className={styles.continue} key={course.id}><span className={styles.progress}>{Math.round((course.completedDays / Math.max(1, course._count.days)) * 100)}%</span><div><b>{course.title}</b><p>{course.academy} · Next: Day {Math.min(course._count.days, course.completedDays + 1)}</p></div><button onClick={() => openCourse(course.id)}>RESUME →</button></div>)}{!data.enrolled.length && <div className={styles.empty}>Choose your first course from the catalog.</div>}</section><aside><header className={styles.sectionTitle}><h2>Academic snapshot</h2></header><div className={styles.metrics}><div className={styles.metric}><small>CURRICULUM COVERAGE</small><strong>{data.coverage.mapped}/{data.coverage.total}</strong></div><div className={styles.metric}><small>COMPLETED COURSE DAYS</small><strong>{data.enrolled.reduce((total, course) => total + course.completedDays, 0)}</strong></div><div className={styles.metric}><small>LEARNING CREDITS</small><strong>{records?.learningCredits || 0}</strong></div></div></aside></div></section>;

  if (view === "catalog") return <section className={styles.learning}><header className={styles.catalogHead}><div><p>16 ACADEMIES · SOURCE-GROUNDED CURRICULUM</p><h1>Course catalog</h1></div><p>{filtered.length} OF {data.courses.length} COURSES</p></header><div className={styles.filters}><input aria-label="Search courses" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search subjects, titles, or course codes"/><select aria-label="Academy" value={academy} onChange={(event) => setAcademy(event.target.value)}><option value="ALL">All academies</option>{data.academies.map((name) => <option key={name}>{name}</option>)}</select><select aria-label="Level" value={level} onChange={(event) => setLevel(event.target.value)}><option value="ALL">All levels</option>{["FOUNDATION", "INTERMEDIATE", "ADVANCED", "CAPSTONE"].map((name) => <option key={name}>{name}</option>)}</select></div><div className={styles.courseList}>{filtered.map((course) => <article className={styles.course} key={course.id}><span className={styles.courseCode}>{course.code}</span><div><h3>{course.title}</h3><p>{course.summary}</p><small>{course.academy} · {course.prerequisites.length ? `Requires ${course.prerequisites.map((item) => item.prerequisite.code).join(", ")}` : "Open enrollment"}</small></div><div className={styles.courseMeta}><b>{course.estimatedDays} DAYS · {course.workloadHours} HOURS</b><small>{course.learningCredits} CREDITS · {course._count.enrollments} ENROLLED</small><small>{money(course.serviceValueCents)} SPONSORED VALUE</small></div>{course.enrollments.length ? <button className={styles.primary} onClick={() => openCourse(course.id)}>OPEN COURSE →</button> : <button onClick={() => enroll(course)}>ENROLL · $0 DUE</button>}</article>)}</div></section>;

  if (view === "programs") return <RecordPage title="Academic programs" eyebrow="PATHWAYS AND PROGRESSION">{records?.programs.map((program) => <article className={styles.record} key={program.id}><span>{program.code} · {program.level}</span><div><h3>{program.title}</h3><p>{program.summary}</p></div><b>{program.creditsRequired} CREDITS</b></article>)}</RecordPage>;
  if (view === "submissions") return <RecordPage title="Assignments and feedback" eyebrow="STUDIO ASSESSMENT RECORD">{records?.submissions.map((submission) => <article className={styles.record} key={submission.id}><span>{submission.status.replaceAll("_", " ")}</span><div><h3>{submission.title}</h3><p>{submission.course.code} · {submission.course.title}{submission.feedback ? ` · ${submission.feedback}` : ""}</p></div></article>)}{!records?.submissions.length && <div className={styles.empty}>Final course artifacts and faculty feedback will appear here.</div>}</RecordPage>;
  return <RecordPage title="Academic record" eyebrow="CREDENTIALS AND COMPLETION">{records?.certificates.map((certificate) => <article className={styles.record} key={certificate.id}><span>{new Date(certificate.issuedAt).toLocaleDateString()}</span><div><h3>{certificate.title}</h3><p>{certificate.issuer} · {certificate.learningCredits} credits</p></div><Link href={`/credentials/${certificate.credentialCode}`}>VERIFY ↗</Link></article>)}{!records?.certificates.length && <div className={styles.empty}>Approved capstone work will issue credentials here.</div>}</RecordPage>;
}

function CoursePlayer({ course, close, refresh }: { course: CourseDetail; close: () => void; refresh: () => Promise<void> }) {
  const firstOpen = course.days.findIndex((day) => !day.progress[0]?.completed); const [index, setIndex] = useState(firstOpen < 0 ? 0 : firstOpen); const [answer, setAnswer] = useState(""); const [reflection, setReflection] = useState(""); const [message, setMessage] = useState(""); const day = course.days[index];
  async function complete() { const response = await fetch(`/api/curriculum/${course.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ dayId: day.id, answer, reflection }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error); return; } setMessage(`Day complete · course progress ${result.progress}%`); setAnswer(""); setReflection(""); await refresh(); }
  const allDone = course.days.every((item) => item.progress[0]?.completed);
  return <section className={styles.player}><aside className={styles.toc}><button onClick={close}>← COURSE CATALOG</button><h2>{course.title}</h2><p>{course.code} · {course.estimatedDays} days · {course.academy}</p><nav aria-label="Course table of contents">{course.days.map((item, itemIndex) => <button className={`${itemIndex === index ? styles.on : ""} ${item.progress[0]?.completed ? styles.done : ""}`} key={item.id} onClick={() => setIndex(itemIndex)}><i>{item.progress[0]?.completed ? "✓" : item.dayNumber}</i><span>{item.title}</span></button>)}</nav></aside><article className={styles.lesson}><header><p>DAY {day.dayNumber} OF {course.days.length} · {course.academy.toUpperCase()}</p><h1>{day.title}</h1><span>{course.studio}</span></header><section className={styles.objectives}><h3>LEARNING OBJECTIVES</h3><ul>{day.objectives.map((objective) => <li key={objective}>{objective}</li>)}</ul></section><section className={styles.lessonBlock}><h3>INSTRUCTION</h3><p>{day.instructionalText}</p></section><section className={styles.lessonBlock}><h3>WORKBENCH PROCEDURE</h3><ol className={styles.steps}>{day.workbenchSteps.map((step) => <li key={step}>{step}</li>)}</ol></section><section className={styles.lessonBlock}><h3>PRACTICAL LAB</h3><p>{day.practicalLab}</p><ul>{day.completionChecklist.map((item) => <li key={item}>{item}</li>)}</ul></section>{course.sources[0] && <section className={styles.source}><b>BOHEMIA INTERACTIVE TECHNICAL SOURCE</b><p>{day.sourceSection}</p><small>Revision {course.sources[0].revisionId || "awaiting first sync"} · {course.sources[0].syncStatus}</small><a href={course.sources[0].url} target="_blank" rel="noreferrer">OPEN OFFICIAL WIKI SOURCE ↗</a></section>}<section className={styles.completion}><h3>KNOWLEDGE CHECK</h3><p>{day.knowledgeQuestion}</p><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Explain your answer with evidence…"/><h3>DEVELOPMENT REFLECTION</h3><p>{day.reflectionPrompt}</p><textarea value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="Record the decision, evidence, and next verification…"/><button onClick={complete}>COMPLETE DAY {day.dayNumber} →</button>{message && <p>{message}</p>}</section>{allDone && course.enrollments[0]?.status !== "COMPLETED" && <FinalSubmission course={course}/>}<footer className={styles.lessonNav}><button disabled={index === 0} onClick={() => setIndex(index - 1)}>← PREVIOUS</button><button disabled={index === course.days.length - 1} onClick={() => setIndex(index + 1)}>NEXT DAY →</button></footer></article></section>;
}

function FinalSubmission({ course }: { course: CourseDetail }) { const [message, setMessage] = useState(""); return <form className={styles.finalSubmission} onSubmit={async (event) => { event.preventDefault(); const response = await fetch("/api/academy", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "submit_mod", courseId: course.id, ...Object.fromEntries(new FormData(event.currentTarget)) }) }); const result = await response.json(); setMessage(response.ok ? "Submitted to studio faculty for assessment." : result.error); }}><h3>Final studio assessment</h3><p>{course.deliverable} Submit the technical record here; external evidence is optional and no files are stored by Enfusion University.</p><input name="title" required minLength={3} placeholder="Artifact title"/><textarea name="summary" required minLength={30} placeholder="Explain the outcome, architecture, testing evidence, and lessons learned…"/><input name="referenceUrl" type="url" placeholder="Optional Workshop, wiki, video, or issue reference"/><input name="demoUrl" type="url" placeholder="Optional demonstration URL"/><button>SEND TO STUDIO REVIEW →</button>{message && <p>{message}</p>}</form> }

function RecordPage({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) { return <section className={styles.learning}><header className={styles.catalogHead}><div><p>{eyebrow}</p><h1>{title}</h1></div></header><div className={styles.recordList}>{children}</div></section>; }
