"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Award = { academicIdentity: string; studentNumber: string; estimatedProgramValueCents: number; grantAwardCents: number; studentDueCents: number; availableGrantBalanceCents: number; breakdown: { label: string; amountCents: number }[]; disclosure: string };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);

export function UniversityRegistrationForm({ existingEmail = "", existingName = "" }: { existingEmail?: string; existingName?: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [award, setAward] = useState<Award | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const entries = Object.fromEntries(new FormData(event.currentTarget)); const data = { ...entries, acceptPolicies: Boolean(entries.acceptPolicies), grantAcknowledgement: Boolean(entries.grantAcknowledgement) }; const response = await fetch("/api/auth/university-register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) { setError(result.error || "Application could not be completed."); setBusy(false); return; } setAward(result.award); window.scrollTo({ top: 0, behavior: "smooth" }); }
  if (award) return <main className="awardPage"><section className="awardDecision"><header><div className="awardSeal">EU</div><div><p>ENFUSION UNIVERSITY</p><strong>AUTOMATED ADMISSIONS + SPONSORSHIP DECISION</strong></div><span>ADMITTED</span></header><div className="awardHero"><p>WELCOME TO THE CLASS OF 2026</p><h1>Your application has been<br/><em>approved and fully sponsored.</em></h1><span>Your EFU academic identity and Thunder Buddies Studios Sponsored Learning Grant are active immediately.</span></div><div className="awardIdentity"><div><small>EFU IDENTITY</small><strong>{award.academicIdentity}</strong><span>Internal campus login identifier · not an internet mailbox</span></div><div><small>STUDENT NUMBER</small><strong>{award.studentNumber}</strong><span>Permanent learner record identifier</span></div></div><section className="awardStatement"><header><h2>Sponsored learning statement</h2><code>DECISION / AUTO-GRANT-APPROVED</code></header>{award.breakdown.map((item) => <div key={item.label}><span>{item.label}</span><b>{money(item.amountCents)}</b></div>)}<div className="statementTotal"><span>ESTIMATED PROGRAM SERVICE VALUE</span><b>{money(award.estimatedProgramValueCents)}</b></div><div className="statementGrant"><span>THUNDER BUDDIES STUDIOS SPONSORED LEARNING GRANT</span><b>− {money(award.grantAwardCents)}</b></div><div className="statementDue"><span>STUDENT AMOUNT DUE</span><b>{money(award.studentDueCents)}</b></div></section><section className="grantBalance"><div><small>AVAILABLE FOR FUTURE ONLINE COURSES</small><strong>{money(award.availableGrantBalanceCents)}</strong><span>NON-CASH SPONSORED LEARNING BALANCE</span></div><p>Course service values are allocated against this balance when you enroll. You will see every allocation in your student record and will never be charged through this system.</p></section><p className="awardDisclosure">{award.disclosure}</p><button onClick={() => { router.push("/university"); router.refresh(); }}>ENTER ENFUSION UNIVERSITY →</button></section></main>;

  return <main className="admissionsPage"><header className="admissionsHeader"><Link href="/" className="universityBrand"><b>EU</b><span><strong>ENFUSION</strong><small>UNIVERSITY</small></span></Link><div><span>OFFICE OF ADMISSIONS</span><b>2026 ONLINE APPLICATION</b></div><Link href="/university/login">STUDENT SIGN IN →</Link></header><div className="admissionsLayout"><aside><p>APPLICATION SECTIONS</p>{["Identity + Contact", "Technical Background", "Academic Intent", "Sponsorship", "Certification"].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><b>{item}</b></div>)}<section><strong>$0 STUDENT COST</strong><p>Every admitted learner is considered for the Thunder Buddies Studios Sponsored Learning Grant.</p></section></aside><form className="admissionsForm" onSubmit={submit}><div className="admissionsIntro"><p>ENFUSION UNIVERSITY / COMMUNITY ADMISSIONS</p><h1>Student registration<br/>and sponsorship application</h1><span>Complete every section carefully. This application establishes your academic identity, learner record, course placement, and sponsored-learning balance.</span></div>
    <fieldset><legend><span>01</span><div><b>Identity and contact</b><small>Information used to establish your secure learner record.</small></div></legend><div className="fieldGrid"><label className="wide">FULL LEGAL / PUBLIC NAME<input name="name" defaultValue={existingName} required minLength={2} autoComplete="name" placeholder="Alex Morgan"/></label><label>PREFERRED NAME <small>OPTIONAL</small><input name="preferredName" placeholder="Alex"/></label><label>RECOVERY EMAIL<input name="email" defaultValue={existingEmail} readOnly={Boolean(existingEmail)} required type="email" autoComplete="email" placeholder="alex@example.com"/></label><label>COUNTRY OR REGION<input name="country" required placeholder="United States"/></label><label>TIME ZONE<input name="timeZone" required defaultValue={Intl.DateTimeFormat().resolvedOptions().timeZone} placeholder="America/New_York"/></label><label className="wide">CREATE PASSWORD<input name="password" required type="password" minLength={10} autoComplete="new-password" placeholder="At least 10 characters"/></label></div></fieldset>
    <fieldset><legend><span>02</span><div><b>Technical background</b><small>Used for course placement—not to exclude new developers.</small></div></legend><div className="fieldGrid"><label>EXPERIENCE LEVEL<select name="experienceLevel" required><option value="">Select level</option><option value="NEW">New to game development</option><option value="BEGINNER">Beginner / guided projects</option><option value="INTERMEDIATE">Intermediate / shipped small mods</option><option value="ADVANCED">Advanced / complex systems</option><option value="PROFESSIONAL">Professional development experience</option></select></label><label>PRIMARY CONCENTRATION<select name="specialty" required><option>Enfusion scripting</option><option>Game systems design</option><option>Terrain and world building</option><option>3D assets and vehicles</option><option>Animation</option><option>Audio design</option><option>Quality assurance</option><option>Technical production</option></select></label><label className="wide">ARMA REFORGER WORKBENCH EXPERIENCE<textarea name="workbenchExperience" required minLength={20} placeholder="Describe tools used, projects attempted, published mods, or what you want to learn first…"/></label><label className="wide">ENFORCE SCRIPT / PROGRAMMING EXPERIENCE<textarea name="enforceExperience" required minLength={20} placeholder="Describe Enforce Script, C#, C++, JavaScript, Python, or other technical experience. New developers may write ‘No prior programming experience’ and explain their interest."/></label><label>WEEKLY STUDY AVAILABILITY<input name="weeklyHours" required type="number" min="1" max="60" defaultValue="8"/><small>Hours per week</small></label><label>GITHUB PROFILE <small>OPTIONAL</small><input name="githubUrl" type="url" placeholder="https://github.com/…"/></label><label className="wide">PORTFOLIO / WORKSHOP PAGE <small>OPTIONAL</small><input name="portfolioUrl" type="url" placeholder="https://…"/></label></div></fieldset>
    <fieldset><legend><span>03</span><div><b>Academic intent</b><small>Tell faculty what you want to build and where you want to advance.</small></div></legend><label>LEARNING GOALS AND PROFESSIONAL DIRECTION<textarea name="learningGoals" required minLength={80} placeholder="In detail, describe the mods you want to create, skills you want to master, roles you want to pursue, and what successful completion would mean to you…"/></label></fieldset>
    <fieldset><legend><span>04</span><div><b>Sponsored-learning application</b><small>All courses are offered at $0 student cost through community sponsorship.</small></div></legend><div className="grantPreview"><div><small>ESTIMATED PROGRAM SERVICE VALUE</small><strong>$42,750</strong></div><div><small>AVAILABLE TBS GRANT AWARD</small><strong>UP TO $50,000</strong></div><p>These are transparent internal estimates for instruction, mentorship, technical infrastructure, assessment, and credential services. They are not tuition prices or cash awards.</p></div><label>WHY WOULD SPONSORED ACCESS HELP YOU COMPLETE THIS PROGRAM?<textarea name="fundingStatement" required minLength={40} placeholder="Describe barriers to paid training, your commitment to completing free coursework, and how you would use this opportunity responsibly…"/></label><label>ACCESSIBILITY OR LEARNING SUPPORT <small>OPTIONAL / PRIVATE</small><textarea name="supportNeeds" placeholder="Describe accommodations, scheduling constraints, assistive technology, or other support that would help you participate."/></label></fieldset>
    <fieldset><legend><span>05</span><div><b>Certification and policies</b><small>Required acknowledgements before submission.</small></div></legend><label className="checkField"><input name="acceptPolicies" type="checkbox" required/><span>I certify that the application is accurate and agree to institutional conduct, academic integrity, portfolio review, and learner-record policies.</span></label><label className="checkField"><input name="grantAcknowledgement" type="checkbox" required/><span>I understand the Thunder Buddies Studios grant is non-cash, is not federal student aid, creates no debt, and is only an internal sponsored-learning balance. Enfusion University programs are independently operated and non-accredited unless formally recognized.</span></label></fieldset>{error && <p className="admissionsError">△ {error}</p>}<div className="admissionsSubmit"><p>By submitting, you authorize automated creation of your EFU identity, admissions decision, sponsorship statement, and learner record.</p><button disabled={busy}>{busy ? "CALCULATING ADMISSION + GRANT…" : "SUBMIT APPLICATION →"}</button></div></form></div></main>;
}
