export const academies = [
  ["Workbench Foundations", "Resource Manager", ["Mod Project Setup", "Workbench Interface and Editors", "Project Dependencies", "Publishing a First Addon", "Addon Architecture", "Workbench Preferences and Shortcuts", "Diagnostic Console", "Project Templates", "Dependency Conflict Resolution", "Collaborative Mod Planning", "Workbench Production Sprint", "Foundation Portfolio Capstone"]],
  ["Resource Management", "Resource Manager", ["Resource Browser and Data Structure", "Prefab Foundations", "Configuration Files", "Resource Validation and GUIDs", "Resource Inheritance", "Prefab Variants", "Metadata and Import Settings", "Resource Naming Standards", "Dependency Auditing", "Large Addon Organization", "Resource Migration Studio", "Resource Pipeline Capstone"]],
  ["Enforce Scripting", "Script Editor", ["Enforce Script Syntax", "Object-Oriented Programming", "Scripting Conventions", "Script Modding and Overrides", "Collections and Data Types", "Events and Callbacks", "Component Scripting", "Debugging Enforce Code", "Performance-Aware Scripting", "Reusable Script Architecture", "Script Systems Studio", "Enforce Engineering Capstone"]],
  ["Gameplay Systems", "World Editor", ["Entity Components", "User Actions", "Game Modes and Services", "Gameplay Systems Capstone", "Inventory and Equipment", "Damage and Health Systems", "Interaction Design", "Persistence Patterns", "Player Lifecycle", "Mission Rule Architecture", "Gameplay Feature Studio", "Integrated Gameplay Capstone"]],
  ["Multiplayer Replication", "Script Editor", ["Authority and Ownership", "Replication Basics", "Remote Procedure Calls", "Multiplayer Reliability Capstone", "Replicated Properties", "Join in Progress", "Network Relevancy", "Prediction and Reconciliation", "Persistent Multiplayer State", "Replication Profiling", "Networked Feature Studio", "Distributed Systems Capstone"]],
  ["World and Terrain", "World Editor", ["World Editor Foundations", "Terrain Creation", "Layers Roads and Biomes", "Playable World Capstone", "Heightmaps and Terrain Data", "Water and Coastlines", "Forest and Vegetation Systems", "Road Networks", "World Composition", "Terrain Performance", "Playable Region Studio", "World Production Capstone"]],
  ["Artificial Intelligence", "World Editor", ["AI Foundations", "Navmesh Generation", "AI Waypoints and Behavior", "AI Scenario Capstone", "AI Groups and Formations", "Perception and Threat Systems", "Smart Objects", "Tactical Behavior Design", "Vehicle AI", "AI Debugging and Profiling", "Combat Encounter Studio", "AI Systems Capstone"]],
  ["Interface and Localization", "Workbench", ["UI Layout Foundations", "Widgets and Event Handling", "Localization Tables", "Accessible Interface Capstone", "Layout Containers", "Data Binding Patterns", "Input and Focus Navigation", "HUD Architecture", "Menu State Management", "Multilingual Production", "Interface System Studio", "Player Experience Capstone"]],
  ["Audio Production", "Audio Editor", ["Audio Editor Foundations", "Signals Nodes and Shaders", "Entity Sound Integration", "Interactive Audio Capstone", "Sound Project Organization", "Weapon Audio Layers", "Vehicle Audio Systems", "Environmental Ambience", "Spatial Audio", "Audio Performance and Mixing", "Interactive Soundscape Studio", "Audio Production Capstone"]],
  ["Animation", "Animation Editor", ["Animation Foundations", "Animation Graphs", "Procedural Animation", "Character Animation Capstone", "Animation Import Pipeline", "State Machines", "Inverse Kinematics", "Weapon Animation", "Vehicle Animation", "Animation Debugging", "Interactive Motion Studio", "Animation Systems Capstone"]],
  ["VFX and Materials", "Particle Editor", ["Material Foundations", "Textures and Import", "Particles and Effects", "VFX Integration Capstone", "Physically Based Materials", "Material Instances", "Decals and Surface Effects", "Weather Effects", "Weapon and Impact VFX", "VFX Performance", "Effects Sequence Studio", "Visual Effects Capstone"]],
  ["Weapons", "World Editor", ["Weapon Modding", "Weapon Asset Preparation", "Optics Collimators and Attachments", "Production Weapon Capstone", "Weapon Configuration", "Ammunition and Ballistics", "Muzzles and Fire Modes", "Reload Systems", "Weapon Handling", "Weapon Testing and Balance", "Weapon Family Studio", "Armament Production Capstone"]],
  ["Vehicles", "World Editor", ["Vehicle Modding", "Vehicle Asset Preparation", "Simulation Components", "Production Vehicle Capstone", "Vehicle Configuration", "Wheels Tracks and Suspension", "Vehicle Damage", "Turrets and Compartments", "Vehicle Audio and VFX", "Vehicle Networking", "Vehicle Variant Studio", "Vehicle Production Capstone"]],
  ["Characters and Factions", "World Editor", ["Character Gear Foundations", "Rigging and Protection", "Faction Creation", "Playable Faction Capstone", "Character Asset Pipeline", "Clothing and Equipment", "Loadout Systems", "Character Damage Zones", "Faction Services and Catalogs", "Character Optimization", "Faction Content Studio", "Character Production Capstone"]],
  ["Scenarios and Game Master", "World Editor", ["Scenario Framework", "Game Master Integration", "Tasks Respawn and Objectives", "Multiplayer Scenario Capstone", "Scenario Properties", "Spawn and Deployment Systems", "Task Flow Design", "Game Master Editable Entities", "Dynamic Events", "Scenario Persistence", "Combined Arms Scenario Studio", "Mission Design Capstone"]],
  ["Quality and Publishing", "Workbench", ["Debugging and Diagnostics", "Performance and Optimization", "Workshop Publishing", "Release Readiness Capstone", "Test Plan Design", "Automated Validation", "Compatibility Testing", "Server Profiling", "Workshop Metadata", "Release Operations", "Certification Test Studio", "Publishing and Support Capstone"]],
];

export function wikiTitle(subject) {
  const explicit = {
    "Mod Project Setup": "Arma Reforger:Mod Project Setup", "Resource Browser and Data Structure": "Arma Reforger:Data Modding Basics",
    "Prefab Foundations": "Arma Reforger:Prefabs Basics", "Enforce Script Syntax": "Arma Reforger:Enforce Script Syntax",
    "Scripting Conventions": "Arma Reforger:Scripting: Conventions", "Script Modding and Overrides": "Arma Reforger:Scripting Modding",
    "Navmesh Generation": "Arma Reforger:Navmesh Tutorial", "Audio Editor Foundations": "Arma Reforger:Audio Editor: Getting Started Tutorial",
    "Animation Foundations": "Arma Reforger:Animation Editor", "Animation Graphs": "Arma Reforger:Animation Editor",
    "Procedural Animation": "Arma Reforger:Procedural Animation Editor", "Animation Import Pipeline": "Arma Reforger:Enfusion Blender Tools: Import/Export Animation",
    "State Machines": "Arma Reforger:Animation Editor", "Inverse Kinematics": "Arma Reforger:Animation Editor",
    "Weapon Animation": "Arma Reforger:Weapon Animation Basic Creation", "Animation Debugging": "Arma Reforger:Animation Editor",
    "Weapon Modding": "Arma Reforger:Weapon Modding",
    "Weapon Asset Preparation": "Arma Reforger:Weapon Creation/Asset Preparation", "Vehicle Modding": "Arma Reforger:Car Modding",
    "Vehicle Asset Preparation": "Arma Reforger:Car Creation/Asset Preparation", "Faction Creation": "Arma Reforger:Faction Creation",
    "Game Master Integration": "Arma Reforger:Game Master Tutorial", "Workshop Publishing": "Arma Reforger:Workshop",
  };
  return explicit[subject] || `Arma Reforger:${subject}`;
}

export function sourceUrl(title) { return `https://community.bohemia.net/wiki/${encodeURIComponent(title.replaceAll(" ", "_"))}`; }

const studioDays = [
  { stage: "Orient", focus: "establish the tool, project, dependencies, and safe working boundary", actions: ["Create or open the disposable training addon and confirm its project root.", "Open the assigned editor from the Workbench toolbar and identify the panels used by the source procedure.", "Record the starting project state before changing a resource."] },
  { stage: "Inspect", focus: "read the existing resource structure before editing it", actions: ["Locate the example resource through Resource Browser rather than a filesystem shortcut.", "Inspect its inheritance, dependencies, and referenced resources.", "Write down which property or component controls the behavior being studied."] },
  { stage: "Reproduce", focus: "recreate the documented baseline without improvisation", actions: ["Follow the mapped source procedure in order inside the training addon.", "Save after each complete operation and note the resulting resource state.", "Run the smallest available preview or test that proves the baseline works."] },
  { stage: "Isolate", focus: "separate one variable from the rest of the system", actions: ["Duplicate or inherit only the resource needed for this experiment.", "Disable unrelated variations so one behavior remains under test.", "Compare the isolated result with the unchanged baseline."] },
  { stage: "Configure", focus: "apply deliberate settings and verify their ownership", actions: ["Open the configuration or component named by the source.", "Change one documented field at a time and save the resource.", "Reopen the resource and confirm the value persisted in the addon-owned copy."] },
  { stage: "Implement", focus: "assemble the complete working behavior", actions: ["Connect the required resources, components, or script entry points.", "Compile the project and resolve errors introduced by the implementation.", "Exercise the primary success path in an isolated scenario."] },
  { stage: "Validate", focus: "prove that required states and dependencies are correct", actions: ["Run Workbench validation on every edited resource.", "Review the console from the first new message rather than the final cascade.", "Record the validation result and the exact resource path tested."] },
  { stage: "Debug", focus: "trace a controlled failure to its first cause", actions: ["Create or identify one reproducible failing case.", "Use the console, debugger, or diagnostic visualization appropriate to the editor.", "Correct the first causal issue and rerun the identical test."] },
  { stage: "Integrate", focus: "connect the feature to its surrounding gameplay system", actions: ["Place the validated resource into a minimal integration scenario.", "Confirm inputs, dependencies, ownership, and lifecycle events.", "Test entry, active, and exit states without changing the isolated implementation."] },
  { stage: "Document", focus: "turn the working result into a reproducible technical record", actions: ["Record every addon-owned path and configuration used by the result.", "Write the verification sequence another developer can repeat.", "Capture one known limitation and the evidence supporting it."] },
  { stage: "Extend", focus: "add one bounded variation without breaking the baseline", actions: ["Create a derived variant rather than modifying the verified baseline.", "Change one behavior relevant to the course objective.", "Run baseline and variant side by side and record the difference."] },
  { stage: "Test", focus: "exercise success, failure, and boundary cases", actions: ["Write a small test matrix with expected observable results.", "Run each case from a clean scenario state.", "Record deviations with reproduction steps and console evidence."] },
  { stage: "Review", focus: "audit the implementation against source and course outcomes", actions: ["Compare every technical decision with its mapped Wiki section.", "Remove unused resources, stale references, and unexplained settings.", "Ask whether the evidence proves each stated course outcome."] },
  { stage: "Polish", focus: "improve clarity and usability without hiding defects", actions: ["Normalize names, folders, labels, and presentation details.", "Retest the implementation after each polish change.", "Confirm that no cosmetic change altered the verified behavior."] },
  { stage: "Demonstrate", focus: "produce clear public evidence of the working feature", actions: ["Prepare the smallest scenario that shows the intended behavior.", "Capture the setup, action, visible result, and relevant diagnostic state.", "Write a technical explanation that matches the recorded evidence."] },
  { stage: "Harden", focus: "handle invalid, missing, and repeated states safely", actions: ["Test missing dependencies and invalid configuration values.", "Repeat initialization and teardown to expose lifecycle errors.", "Add only source-supported guards and verify the recovery path."] },
  { stage: "Benchmark", focus: "measure cost and identify the first meaningful constraint", actions: ["Choose one repeatable performance scenario and baseline it.", "Use the relevant Workbench profiler or diagnostic counter.", "Change one factor, rerun the same scenario, and compare evidence."] },
  { stage: "Package", focus: "prepare a clean addon-owned release candidate", actions: ["Audit dependencies and confirm no base-game resource was modified.", "Validate the complete addon and resolve release-blocking messages.", "Record the candidate version, test scenario, and known limitations."] },
  { stage: "Present", focus: "explain architecture, procedure, evidence, and tradeoffs", actions: ["Walk through the resource chain from entry point to visible result.", "Demonstrate the verification test without hidden setup.", "Connect each major decision to source evidence and an observed outcome."] },
  { stage: "Reflect", focus: "consolidate the workflow into future practice", actions: ["Review the development record from baseline through final validation.", "Identify the most expensive mistake and the checkpoint that would catch it earlier.", "Define the next experiment with a specific expected result."] },
];

export function makeDay({ subject, editor, dayNumber, days, source }) {
  const blueprint = studioDays[dayNumber - 1] || { stage: `Studio ${dayNumber}`, focus: "complete a bounded technical milestone", actions: ["Open the verified addon state.", "Complete the documented milestone.", "Validate and record the result."] };
  const stage = blueprint.stage;
  return {
    dayNumber,
    title: `${stage}: ${subject}`,
    objectives: [`Explain the ${stage.toLowerCase()} phase for ${subject}.`, `Complete a repeatable ${editor} workflow.`, "Record evidence and a troubleshooting observation."],
    instructionalText: `Day ${dayNumber} of ${days} focuses on how to ${blueprint.focus} for ${subject}. Use ${editor} in a disposable addon, preserve the verified starting state, and treat each visible result or console message as evidence. This transitional lesson remains available until the source-grounded Guided Studio compiler publishes its fully cited replacement.`,
    sourceSection: `${source} is the mapped technical authority. Use its current verified revision for interface names, resource paths, procedures, warnings, and examples; do not substitute remembered steps.`,
    workbenchSteps: blueprint.actions.map((action, index) => `${index === 0 ? `Open ${editor}. ` : ""}${action}`),
    practicalLab: `Create a small, reversible ${subject} exercise demonstrating the ${stage.toLowerCase()} phase. The result must load without new errors and include a written test case.`,
    completionChecklist: ["Training addon opens", "Resources live inside the addon", "Validation completes", "Behavior is tested", "Development record is updated"],
    knowledgeQuestion: `What evidence proves that the Day ${dayNumber} ${subject} change is isolated, valid, and ready to continue?`,
    knowledgeAnswer: "A clean validation result, a reproducible test, an addon-owned resource path, and a written observation provide the required evidence.",
    reflectionPrompt: `Describe the most important ${subject} decision you made today, what evidence supported it, and what you will verify on Day ${Math.min(days, dayNumber + 1)}.`,
  };
}
