import Link from "next/link";
import { redirect, notFound } from "next/navigation";
import { currentUser, isAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import "./receipt.css";

export default async function ReceiptPage({ params }: { params: Promise<{ signatureEventId: string }> }) {
  const user = await currentUser(); if (!user) redirect("/university/login");
  const { signatureEventId } = await params;
  const event = await db.policySignatureEvent.findUnique({ where: { id: signatureEventId }, include: { acceptances: { orderBy: { policyVersion: { document: { sortOrder: "asc" } } }, include: { policyVersion: { include: { document: true } } } } } });
  if (!event || (event.userId !== user.id && !isAdmin(user.role))) notFound();
  return <main className="receiptPage"><header><Link href="/policies">ENFUSION UNIVERSITY / POLICY CENTER</Link><span>RETAINABLE ELECTRONIC RECORD</span></header><section className="receiptSheet"><span>SIGNATURE RECEIPT</span><h1>Electronic policy acceptance</h1><p className="receiptLead">This record confirms affirmative consent to the exact immutable versions reproduced below. Save or print this HTML page for your records.</p><dl><div><dt>Receipt</dt><dd>{event.receiptNumber}</dd></div><div><dt>Signer</dt><dd>{event.signerName}</dd></div><div><dt>Signed</dt><dd>{event.signedAt.toLocaleString()}</dd></div><div><dt>Adult attestation</dt><dd>{event.ageAttested ? "Affirmed" : "Not recorded"}</dd></div><div><dt>Electronic consent</dt><dd>{event.electronicConsent ? "Affirmed" : "Not recorded"}</dd></div></dl><h2>Accepted documents</h2>{event.acceptances.map((acceptance, index) => { const version = acceptance.policyVersion; const content = version.content as { plainLanguage?: string;sections?:{heading:string;paragraphs:string[];bullets?:string[]}[];sources?:{label:string;url:string}[] }; return <article key={acceptance.id}><i>{String(index + 1).padStart(2,"0")}</i><div><h3>{version.document.title}</h3><code>Version {version.version} · Effective {version.effectiveAt?.toLocaleDateString() || "upon publication"} · SHA-256 {version.checksum}</code><p><strong>Plain-language summary:</strong> {content.plainLanguage}</p>{content.sections?.map(section=><section key={section.heading}><h4>{section.heading}</h4>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.bullets&&<ul>{section.bullets.map(bullet=><li key={bullet}>{bullet}</li>)}</ul>}</section>)}{content.sources?.map(source=><p key={source.url}>{source.label}: <a href={source.url}>{source.url}</a></p>)}</div></article>})}<footer><p>Signed electronically with a typed signature. User-agent and a salted IP hash are retained with the signature event; no drawn signature or raw IP address is stored.</p><p>Joint operators: Thunder Buddies Studios and Black Ridge Studios.</p></footer></section></main>;
}
